<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.8.0" />
        <PackageReference Include="JustSaying" Version="8.0.0" />
        <PackageReference Include="JustSaying.Extensions.DependencyInjection.SimpleInjector" Version="8.1.27-pre.3" />
        <PackageReference Include="JustSaying.Models" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="SimpleInjector" Version="5.5.0" />
        <PackageReference Include="Testcontainers" Version="4.7.0" />
        <PackageReference Include="Testcontainers.LocalStack" Version="4.7.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JustSaying.Naming.EnvironmentServiceNaming\JustSaying.Naming.EnvironmentServiceNaming.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JustSaying.Naming.EnvironmentServiceNaming\JustSaying.Naming.EnvironmentServiceNaming.csproj" />
    </ItemGroup>


</Project>
